### ISSUE TITLE
Issue with Step 2. of the Programming Stack Instructions

### ISSUE THREAD

**Issue by Pemwilliam20** [LeDataSciFi/Discussion#1]
@donbowen @danielappierto 

Each time I attempt to download / launch the Git installer I get this error message. 

**Screenshot attached:** 
![Screen Shot 2020-01-22 at 2 36 28 PM](https://user-images.githubusercontent.com/60153712/72930839-d504be00-3d2a-11ea-926c-1f3c6939a009.png)

**Comment by danielappierto** [comment]
Hey Will,

Follow this [link](https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac) and it will guide you in fixing this issue.

**Comment by Pemwilliam20** [comment]
Hi, Daniel—

That worked, thanks. But I'm curious about the next step, as I'm unable to see / find an application associated with the installation's completion?

**Comment by danielappierto** [comment]
You can test whether it installed correctly by opening Terminal on your Mac, and typing "git --version". If the version is displayed then Git was installed correctly

**Comment by Pemwilliam20** [comment]
Perfect that worked, thanks!

**Comment by donbowen** [comment]
@Pemwilliam20 please close the issue and mark it as solved.

**Comment by Pemwilliam20** [comment]
Done, thanks!
