### ISSUE TITLE
Rubric for Assignment 6

### ISSUE THREAD

**Issue by tdinhjason** [LeDataSciFi/Discussion#101]
@donbowen I think you put the rubric for assignment 5 in the email, just wanted to give you a heads up

**Comment by donbowen** [comment]
Weird, I changed the URL. This should work:

https://raw.githubusercontent.com/LeDataSciFi/LeDataSciFi.github.io/master/assignments/asgn06.md

**Comment by willperacchio** [comment]
Just curious, why are instances for when the first-time home buyer variable is unknown still dropped for Models 2-3 when the First_time_home_buyer variable isn't being evaluated as a regressor anymore? I figured all of the regressions were separate and a few of my coefficients are slightly off at the .01 level or so from those few instances as a result

Also where do we find the answer key's model interpretation section as per the rubric? Or are we just supposed to eyeball to see if what they is in the right ballpark

**Comment by donbowen** [comment]
@willperacchio Updated https://github.com/LeDataSciFi/Discussion/blob/master/A6%20answer%20key.md
