### ISSUE TITLE
Problem Opening Assignment 1's to Peer Review

### ISSUE THREAD

**Issue by NickFerrari** [LeDataSciFi/Discussion#13]
Every time I download and open the assignments that I'm supposed to peer review it gives me this warning message.
![Capture](https://user-images.githubusercontent.com/60153777/73986788-84858700-490c-11ea-9a4a-2ca7215bf6b9.PNG)

@donbowen @danielappierto

**Comment by donbowen** [comment]
Will you copy and paste this issue as an issue in the repo you're describing or drop the name here so I can look into it?

I'm in meetings until noon or one, but will reply to your answer then!

**Comment by NickFerrari** [comment]
It's both of the assignments I'm trying to peer review, so youngkev098 and tomboltes. I save the file on my computer and then every time I try to open it it gives me that error message

**Comment by donbowen** [comment]
I'm able to load them. Can you stop by office hours so we can see what the
issue is on your end?

**Comment by NickFerrari** [comment]
I think I got around the problem. Instead of downloading just the ipynb file I downloaded the entire folder and it worked for me

**Comment by donbowen** [comment]
Great! Yes - I used github desktop to clone the repo to my computer, and
then proceeded from there. When you're done, in Github desktop top, go to
that repo, click the Repository menu, then Remove. You can tell it to move
it to the recycle bin if you want as well.
