### ISSUE TITLE
assignment 2

### ISSUE THREAD

**Issue by rebswamp** [LeDataSciFi/Discussion#16]
hi,
im struggling with going about finding the annualized return per firm. first im not sure how to calculate the annual return given the daily data points.
Secondly,
because there are over 600 unique firms i am not sure how to quickly apply the annual returns

**Comment by danielappierto** [comment]
@rebswamp - So you are given the daily returns for each firm. A starting point is to think of how to use these daily returns and annualize them. Try out the test dataframe posted in the assignment 2 overview, and see if you can replicate the results, and then apply that to the larger dataset. No fancy formulas needed, just the daily returns and a little help from certain pandas functions. Dive a little deeper into pandas 'groupby' functionality and this should help with your second question.
