### ISSUE TITLE
Getting NaN

### ISSUE THREAD

**Issue by mattnj58** [LeDataSciFi/Discussion#18]
I've merged the 2 dataframes, but when I looked at the pct_change on the returns, the first line I get is not a number and the last value is inf. Anyone know how to solve this issue?

edit: this is my output 
![image](https://user-images.githubusercontent.com/25622452/74113136-56a07c80-4b70-11ea-95a7-d61bb8e4aa6f.png)

**Comment by danielappierto** [comment]
@mattnj58 - i’m not sure what you are trying to solve with percentage change. The ‘ret’ column is already the daily return for the given day.
