### ISSUE TITLE
Downloading Files

### ISSUE THREAD

**Issue by ejs221** [LeDataSciFi/Discussion#43]
Hi All,

I am having trouble downloading the files into the input folder. I am not totally sure about this issue here, as either, I may simply not be using the right function to download files, or I have this completely wrong. Let me know if anyone has any advice on downloading the files based on my included code. 

<img width="861" alt="Screen Shot 2020-03-16 at 9 11 46 PM" src="https://user-images.githubusercontent.com/60156713/76812414-25e4e000-67cb-11ea-9a18-d732d1388f4f.png">

**Comment by danielappierto** [comment]
@ejs221 your code right now is simply creating a string equal to the url you're trying to grab, as well as a string that attempts to create the folder you want to save in. You need to iterate through the dataset, create the appropriate url, grab it, and save it to the correct folder. Try to follow that logic in order using the appropriate methods (for loops, try-except-else, etc) and see what you can do.

**Comment by ejs221** [comment]
> @ejs221 your code right now is simply creating a string equal to the url you're trying to grab, as well as a string that attempts to create the folder you want to save in. You need to iterate through the dataset, create the appropriate url, grab it, and save it to the correct folder. Try to follow that logic in order using the appropriate methods (for loops, try-except-else, etc) and see what you can do.

I have been trying to do access and download these files as you mentioned, but have not had any luck. Is there a specific tool or set of tools for this? I think my L13 code was slightly incomplete which is why I am struggling.

**Comment by danielappierto** [comment]
@ejs221 - review the [S&P 500 Scraper](https://github.com/LeDataSciFi/Discussion/issues/31) . It contains almost all of the tools necessary to download the files to the correct folders.
