### ISSUE TITLE
Project Data - Any ideas on traders and their trading habits? 

### ISSUE THREAD

**Issue by mattnj58** [LeDataSciFi/Discussion#54]
Anyone know of a good place to start to find data on traders and their trading habits? ex. someone in Fidelity a certain amount of trades per year

**Comment by willperacchio** [comment]
Not specifically, but these are good places to start looking for a reference:
https://www.kaggle.com/
https://data.world/

**Comment by mattnj58** [comment]
Awesome, I'll take a look. Thanks!
