### ISSUE TITLE
See rubric before Assignment 5 deadline

### ISSUE THREAD

**Issue by anniechabak** [LeDataSciFi/Discussion#56]
Would it be possible for the grading rubric to be uploaded before the assignment is due? For example, I know in assignment 4 that the "creativity" category was graded really toughly. I was wondering if there would be any categories like that in this assignment that we should be extra mindful of? Thanks!

**Comment by donbowen** [comment]
Done! Check out the assignment page. I think it's actually a lot easier to read [here](https://github.com/LeDataSciFi/LeDataSciFi.github.io/blob/master/assignments/asgn05.md) than on the "pretty" website.
