### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by emeskin1226** [LeDataSciFi/Discussion#59]
Hi everyone, 

So I have run into an error where for some reason all the 10Ks I have downloaded are missing a "." before the "txt" in every raw file my code downloaded. I noticed this once I tried to run my for loop code and everything else has checked out to work as well. I didn't have any issues with the downloading 10ks step so I'm not enitrely sure where this issue could've came from. 

Wondering if anyone else has had similiar issues or has any advice?

I uploaded a pic of how it looks in my file explorer below:
<img width="583" alt="Annotation 2020-03-21 211620" src="https://user-images.githubusercontent.com/60156544/77240170-3fb26880-6bb9-11ea-9ccf-03280359cfcc.png">

**Comment by willperacchio** [comment]
Did you have a replace filter on the string by any chance?

And while not ideal, python should be able to open it still

**Comment by emeskin1226** [comment]
I was able to find an alternative solution and figure it out but thank you! @willperacchio
