### ISSUE TITLE
Saving/utilizing NEAR_regex

### ISSUE THREAD

**Issue by gdmiddleton** [LeDataSciFi/Discussion#60]
I am having trouble saving/utilizing/importing the NEAR_regex function.  It seems to be saved in my repo because I have a "NEAR_regex.py" file (looks like a paper with the corner folded down), and have a "_pycache_" folder with "NEAR_regex.cpython-37.pyc" file inside (no clue what that is).  I then tried importing NEAR_regex as NEAR_regex and simply import re (tried multiple different ways), but nothing has seemed to work and I receive errors saying either "NEAR_regex is not defined" or "'module' object is not callable."  How do I fix this? Thanks

**Comment by donbowen** [comment]
Most issues people have had with that file are people who download it incorrectly. Open it in jupyter - it should look like a py file, and not weird.  (Have you ever gotten the function to work in class? If yes, copy the code from the participation folder into the assignment folder. If no, then you need to download it correctly. You should look through earlier discussions - people have brought up and solved the same issue.)

That's my best guess. I'll let other people reply to this further. 

Btw - You should provide more info so people can help effectively. Include **code** in the markdown (essential code only) + error picture.

**Comment by willperacchio** [comment]
Raw python files will automatically import, but if you want it to be in a jupyter notebook and import it, you need a workaround that's described here: https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Importing%20Notebooks.html
