### ISSUE TITLE
problem saving data with new risk columns to output folder 

### ISSUE THREAD

**Issue by thugo220** [LeDataSciFi/Discussion#63]
I am attempting to save the new DF to my output folder using this line: 

data.to_stata('output/ccm_with_risk.dta', write_index = False)

After running, I get the following error: 

"ValueError: Column `conting_Risk` cannot be exported.
Only string-like object arrays containing all strings or a mix of strings and None can be exported. Object arrays containing only null values are prohibited. Other object typescannot be exported and must first be converted to one of the supported types."

-  "data" is the original DF from my input folder with all the new risk factor columns added to it.
-  "conting_Risk" is one of the risk columns. it contains ints and NaN in the rows without 10K data. 

Has anyone else had a similar issue or know what the problem might be? Thank you

**Comment by donbowen** [comment]
We need more info. Clearly, that variable contains objects that aren't what you think they are.

Reply with a printout of that variables first X rows, last X rows, a printout of the describe for that variable, and potentially, a value_counts() of it.

**Comment by thugo220** [comment]
<img width="471" alt="Screen Shot 2020-03-22 at 5 53 08 PM" src="https://user-images.githubusercontent.com/38572774/77261600-0126b780-6c66-11ea-9b89-131e0fa70253.png">

**Comment by donbowen** [comment]
data.head(10)?

**Comment by thugo220** [comment]
<img width="1102" alt="Screen Shot 2020-03-22 at 6 08 19 PM" src="https://user-images.githubusercontent.com/38572774/77261866-1e5c8580-6c68-11ea-97d8-c4cfdf6854b7.png">

The 6 right most  columns are the risk factors I added.

**Comment by thugo220** [comment]
I might have figured it out.  Changing all the risk columns to type string.

**Comment by donbowen** [comment]
Very weird. That column _appears_ to be a mix of ints and NaNs which should be fine. You could coerce it into an integer column which should force any string that snuck in to convert to nan. Tough to say from here. Good luck!

**Comment by thugo220** [comment]
Thanks for the tips!
