### ISSUE TITLE
Issue with .gitignore 

### ISSUE THREAD

**Issue by jzebaida** [LeDataSciFi/Discussion#65]
Hi guys,
Any idea why github would be ignoring my .gitignore? My input files keep showing up on github.
![image](https://user-images.githubusercontent.com/9028814/77273479-19a8c900-6c8a-11ea-87ad-14ff5c97611b.png)

Thanks

**Comment by andywu50** [comment]
Just type: “/edgar_filings/*”

**Comment by jzebaida** [comment]
> Just type: “/edgar_filings/*”

that is what I have typed in above

**Comment by DanielFajardoGitHub** [comment]
Could you show us where you're storing edgar filings on your desktop?

**Comment by jzebaida** [comment]
> Could you show us where you're storing edgar filings on your desktop?
I included the full directory path and still my github shows the files
![image](https://user-images.githubusercontent.com/9028814/77273840-eca8e600-6c8a-11ea-9c4a-2a9b91bdbb8c.png)

**Comment by mattnj58** [comment]
Did you commit/push your edgar_filings by accident before?

**Comment by jzebaida** [comment]
> Did you commit/push your edgar_filings by accident before?

I did commit them before, would I have to delete them? If so, where would I go about doing that?

**Comment by DanielFajardoGitHub** [comment]
You can just delete them on Jupyter, push the changes and then re-download your 10ks

**Comment by mattnj58** [comment]
Ah then you need to delete it in github desktop and then commit and push the changes

**Comment by jzebaida** [comment]
Was resolved by deleting, committing, and then rerunning my code.
Thanks for the help
