### ISSUE TITLE
No Idea What Happened

### ISSUE THREAD

**Issue by NickFerrari** [LeDataSciFi/Discussion#66]
I tried uploading my changes to github desktop and I get this error:

![Annotation 2020-03-23 134949](https://user-images.githubusercontent.com/60153777/77357083-30443400-6d0d-11ea-86b0-647ee5955410.png)

I have no idea what I did but I can't upload anything. I didn't delete any files so I have no clue what's wrong.

@donbowen

**Comment by DanielFajardoGitHub** [comment]
It closed at 3:00 p.m.

**Comment by willperacchio** [comment]
I think it's because the assignment had a hard cut off deadline of 3PM if I'm remembering correctly. It's a permissions issue, and you don't have permission to it anymore.

**Comment by mattnj58** [comment]
I'm assuming you tried committing and pushing changes after 3pm, which closed at 3

**Comment by NickFerrari** [comment]
I thought the assignment said due at 5pm? I'm looking at the lecture schedule right now

**Comment by willperacchio** [comment]
https://github.com/LeDataSciFi/Discussion/issues/42

**Comment by mattnj58** [comment]
You're looking at project proposal, the assignment 5 was due at 3

**Comment by andywu50** [comment]
Yep if you check the schedule here:

<img width="567" alt="Screen Shot 2020-03-23 at 3 59 44 PM" src="https://user-images.githubusercontent.com/60153800/77357966-6ab6cc80-6d1f-11ea-986c-0373089bab51.png">

**Comment by NickFerrari** [comment]
Well RIP

**Comment by donbowen** [comment]
Sorry. I have to be consistent with everyone on this...
