### ISSUE TITLE
Repository 

### ISSUE THREAD

**Issue by TomBolte** [LeDataSciFi/Discussion#7]
<img width="1304" alt="Screen Shot 2020-02-01 at 6 57 20 PM" src="https://user-images.githubusercontent.com/60156553/73600904-883c9680-4525-11ea-99eb-5844c765e4c7.png">

If I go on the GitHub website, it says that assignment 1 is one of my repositories.

<img width="1304" alt="Screen Shot 2020-02-01 at 6 57 31 PM" src="https://user-images.githubusercontent.com/60156553/73600914-be7a1600-4525-11ea-803b-b3598304188f.png">
However, when I go into my repositories it only shows my participation repository

This is making it difficult because my changes won't go through to the GitHub desktop and I can't commit the changes and push to origin. 
<img width="962" alt="Screen Shot 2020-02-01 at 6 58 07 PM" src="https://user-images.githubusercontent.com/60156553/73600926-fbdea380-4525-11ea-9f0e-d35d66eb9d1c.png">
This is what my Github Desktop looks like.
Am I doing something wrong?

**Comment by donbowen** [comment]
You have rights (as a "member") of your assignment repo but the assignment repo is under the class org (ledatascifi).

Your participation repo, in  contrast, is under your user account. 

The first screen shows you have access to which repos. The second shows repos under your account, and again, the assignment repo isn't under your account, but the class org. 

To get the repo on your computer, one option is to go to the repo on github.com, then go to the green "CLONE" button, then copy the URL. In github desktop, select "add" then in the pop up, choose the URL tab. Copy the URL in and choose where on your computer to put it.
