### ISSUE TITLE
Assignment 6 Categorical Variable Question

### ISSUE THREAD

**Issue by hph220** [LeDataSciFi/Discussion#73]
What are the P,R,C and U for the loan purpose? I am assuming that P is "Purchase", R is "Refinance" and U is "Unknown", however, I can't find any information on C. 

What are the 1, 2 and 3 for Mortgage Insurance Type?

**Comment by andywu50** [comment]
I have the same questions! Also, what is the "Product_type" variable, since it is outputting "FRM?"

**Comment by danielappierto** [comment]
@hph220 - P = Purchase
• C = Cash-out Refinance
• R = No Cash-outRefinance
• U = Refinance –Not Specified

**Comment by sophflan** [comment]
FRM is fixed-rate mortgage. All observations in the dataset are this I believe.
