### ISSUE TITLE
Unable to Upload to Proposal Repository

### ISSUE THREAD

**Issue by mattnj58** [LeDataSciFi/Discussion#78]
Anyone else having trouble updating or uploading their final project proposal to the proposal repository? It seems that uploading has been disabled for me

**Comment by jmartindyer** [comment]
I think it has got to be in the readme of the project

**Comment by jmartindyer** [comment]
In the project repo

**Comment by mattnj58** [comment]
just did that and it forked the repo and to commit the changes, i needed to create a pull request

**Comment by mattnj58** [comment]
oops, wasn't supposed to be pushing into the "proposal" repository.
