### ISSUE TITLE
Function #2 instructions are confusing

### ISSUE THREAD

**Issue by fsn220** [LeDataSciFi/Discussion#8]
In the instructions for Function #2 it says to count the number of distinct elements, do not count duplicates, but the function and answers in a previous thread say we're counting overlapping elements (not the distinct ones). I interpreted this as meaning that the overlap is the same elements; so what do you mean by not counting duplicates?

**Comment by danielappierto** [comment]
@fsn220  i.e, if two lists are (1,1,2,3) and (1,1,2,3), the distinct elements in each are (1,2,3), thus your output should be 3 (3 distinct elements that are characteristic of both lists) - see that it did not count the number 1, twice - hence, no duplicates

you can think of it as overlapping elements, without counting elements that appear more than once.
