### ISSUE TITLE
Deleting files and updating .gitignore ON MAC

### ISSUE THREAD

**Issue by gdmiddleton** [LeDataSciFi/Discussion#88]
Can someone please explain how to delete files from a repo and then update the .gitignore so they won't upload again. I have no clue how to do this in the terminal.

**Comment by mattnj58** [comment]
you would want to open the folder, delete the files, go to terminal, type in `cd <path to your repository>` and then type in `git rm -r --cached .`

**Comment by donbowen** [comment]
Are you following these instructions?
https://github.com/LeDataSciFi/LeDataSciFi.github.io/blob/master/participation/submission_prep.md#before-and-after-the-gitignore-is-altered-and-updated

And Matt's reply is correct as well.

**Comment by andywu50** [comment]
I have a mac and ran into trouble with the `cd "<path>"`  direction. I typed `cd "/Users/andywu/Desktop/FIN377-participation"`.

**Comment by donbowen** [comment]
Add an extra slash at the end?

**Comment by mattnj58** [comment]
when trying cd-ing into the directory, you can get the path to the file by right clicking the file, pressing the option key on your keyboard and then you can copy the path to the repository

**Comment by gdmiddleton** [comment]
> you would want to open the folder, delete the files, go to terminal, type in `cd <path to your repository>` and then type in `git rm -r --cached .` then type in `git init .` and `git add *` and the changes should be in your github desktop

@mattnj58 what do you mean by "open the folder"? Should I be looking at the files on my computer or in github? some of the files i am triyng to ignore don't appear in my finder, so i cant delete them that way.

**Comment by anderson-camp** [comment]
I had issues with the path on my mac but this fixed it.
 If you right click on your participation folder on your computer files, at the bottom there should be a "New Terminal at Folder" option. If you click that it will send you straight to the terminal where you can type in the "git rm" part of the instructions.

**Comment by donbowen** [comment]
Come to office hours.
