### ISSUE TITLE
no .gitignore file ?

### ISSUE THREAD

**Issue by maryluchs** [LeDataSciFi/Discussion#90]
Hey guys, does anyone have an idea why I wouldn't have a .gitignore file already created in my participation folder? I can't see it there or in the documents on my computer. Not sure if there's a simple solution for this that I'm missing -- thanks!

**Comment by mattnj58** [comment]
.gitignores are usually hidden files that your finder/file explorer doesn't normally show. if you made one, then it's in there, the best way to access that file is through github desktop
