### ISSUE TITLE
Creating Dummies Within the Contest Model

### ISSUE THREAD

**Issue by NickFerrari** [LeDataSciFi/Discussion#95]
So I created dummy variables for the contest database, and obviously when I run my model on the out-of-sample database it doesn't have those dummies within the dataset. Has anyone created dummies and found a way around this? One hot encoder is what I find online but I'm a bit confused on what exactly to do.

@donbowen @danielappierto

**Comment by donbowen** [comment]
Well the in sample database doesn't have those dummies either initially...
