### ISSUE TITLE
Error when checking final model

### ISSUE THREAD

**Issue by jzebaida** [LeDataSciFi/Discussion#96]
Hey guys,
I am trying to test my final model so that it displays the R2 score but i keep getting this error. Any ideas? Thanks in advance.
![image](https://user-images.githubusercontent.com/9028814/79930243-08341780-8416-11ea-9a0a-5d700805d08b.png)

**Comment by bstacey7** [comment]
you need
`pipeline.fit(X_train, y_train)`

**Comment by donbowen** [comment]
@jzebaida I got yours to work. I simply changed the first cell in the code by inserting one line of code:

```python
# separate out y var
y = fannie_mae['Original_Interest_Rate']
fannie_mae.drop('Original_Interest_Rate',axis=1,inplace=True) # THIS IS NEW
fannie_mae.info()
```
