### ISSUE TITLE
Pickle Error

### ISSUE THREAD

**Issue by ragamike** [LeDataSciFi/Discussion#97]
Was trying to use the following code from Professor Bowen's website to check if my .sav file was working correctly:

<img width="616" alt="Screen Shot 2020-04-21 at 10 03 59 PM" src="https://user-images.githubusercontent.com/58525974/79932828-6106ae80-841c-11ea-943a-682ac89a51b8.png">

But I got the following error and I don't know how to interpret it or fix it:

<img width="788" alt="Screen Shot 2020-04-21 at 10 04 39 PM" src="https://user-images.githubusercontent.com/58525974/79932774-45030d00-841c-11ea-8d32-a4b17c66f659.png">

Anyone have some idea or suggestions?

**Comment by sophflan** [comment]
I'm guessing you created new variables for your model but the original dataset has 35 after getting rid of interest rate, so you'd wanna match up your model with that and get rid of the 3 extra variables. I had a similar issue before but fixed it by doing that

**Comment by donbowen** [comment]
@sophflan is right. In fact, Issue #96 is the same. My answer there should work here too.
